# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # 这个模块是用于调试功能的
    # 在这里继续添加你所需要的模块
    ]
    # Pods for Demo
    
    target 'Demo-tvOSTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'DemoTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
